name: Continuous Integration
on: 
  push:
    branches:
      - master

env:
  node-version: 14.15.1

jobs:
  
  Build-and-send-to-VPS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: Build application
        working-directory: .
        run: |
          chmod +x .build.sh
          ./.build.sh
        
      - name: Copy app folder content to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: www
          remote: portfolio
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT}}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}

      - name: Restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT}}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd portfolio
            docker-compose down && docker-compose up -d